name: Deploy on EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Push to EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            
            - name: Execute remote SSH commands using SSH key
              uses: appleboy/ssh-action@v1
              with:
                host: 3.87.96.72
                username: ubuntu
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: whoami
            
